approve_by_comment: true
approve_regex: "\\b[aA][pP]+[rR][oO][vV][eE][dD]?\\b"
reject_regex: "\\b[rR][eE][jJ][eE][cC][tT]([eE][dD])?\\b"
reset_on_push: true
reviewers:
  -
    conditions:
      branches:
        - master
    members:
      - bonpixel
      - codetothepoint
      - mhewson
      - megafatsquirrel
      - OwlbearMedia
      - panganibanpj
      - peripateticus
      - petersgrandadventure
      - rhuded
      - lancetharper
    name: default
    required: 1
