approve_by_comment: true
approve_regex: \b[aA][pP]+[rR][oO][vV][eE][dD]?\b
reject_regex: \b[rR][eE][jJ][eE][cC][tT]([eE][dD])?\b
reset_on_push: false
reviewers:
  members:
  - bonpixel
  - codetothepoint
  - mhewson
  - OwlbearMedia
  - panganibanpj
  - peripateticus
  - petersgrandadventure
  - rhuded
  name: default
  required: 1
