module.exports = {
  parser: 'postcss-html',
  syntax: 'postcss-scss',
  plugins: {
    'postcss-import': {},
    'postcss-strip-inline-comments': {},
    'postcss-simple-vars': {},
    'postcss-calc': {},
    'postcss-nested': {},
    'postcss-media-minmax': {},
    'postcss-custom-media': {},
    'postcss-responsive-type': {},
    'postcss-pxtorem': {
      rootValue: 10,
      unitPrecision: 5,
      propList: ['*'],
      selectorBlackList: [/^html$/],
      mediaQuery: false,
      minPixelValue: 0,
    },
    'postcss-inline-svg': {},
    autoprefixer: {},
    cssnano: {},
  },
};
