const fs = require('fs-extra');
const download = require('download');
const glob = require('glob');
const path = require('path');
const _ = require('lodash');

const iconPath = 'src/assets/icons';
const manifestPath = 'src/components/icons/iconComps.js';

// clean directory
fs.emptyDirSync(iconPath);

// fetch icons and create sprite
download('https://assets.brand.ai/rei-digital-experience-team/digital-rei-brand/icons.zip?key=SyQifqFje', iconPath, { extract: true }).then(() => {
  const files = glob.sync('./src/assets/icons/*.svg');

  // remove file to be overwritten
  fs.removeSync(manifestPath);

  let fileContents = `// File generated by utils/icons.js
import Vue from 'vue';
`;
  let exportStr = `
export default {
`;

  files.forEach((file) => {
    const fName = path.basename(file, '.svg');
    const fNameCamel = _.camelCase(path.basename(file, '.svg'));

    fileContents += `
const ${fNameCamel}Tmpl = require('../../assets/icons/${path.basename(file)}');
`;
    fileContents += `
const ${fNameCamel} = Vue.component('${fName}', {
  template: ${fNameCamel}Tmpl,
});
`;
    exportStr += `  ${fNameCamel},
`;
  });

  fileContents += `${exportStr}};
`;

  fs.outputFileSync(manifestPath, fileContents, 'utf8');
});
