// File generated by utils/icons.js
import Vue from 'vue';

const iconReiAddTmpl = require('../../assets/icons/icon-rei-add.svg');

const iconReiAdd = Vue.component('icon-rei-add', {
  template: iconReiAddTmpl,
});

const iconReiBackorderTmpl = require('../../assets/icons/icon-rei-backorder.svg');

const iconReiBackorder = Vue.component('icon-rei-backorder', {
  template: iconReiBackorderTmpl,
});

const iconReiCalendarTmpl = require('../../assets/icons/icon-rei-calendar.svg');

const iconReiCalendar = Vue.component('icon-rei-calendar', {
  template: iconReiCalendarTmpl,
});

const iconReiCallTmpl = require('../../assets/icons/icon-rei-call.svg');

const iconReiCall = Vue.component('icon-rei-call', {
  template: iconReiCallTmpl,
});

const iconReiCartEmptyTmpl = require('../../assets/icons/icon-rei-cart-empty.svg');

const iconReiCartEmpty = Vue.component('icon-rei-cart-empty', {
  template: iconReiCartEmptyTmpl,
});

const iconReiCartTmpl = require('../../assets/icons/icon-rei-cart.svg');

const iconReiCart = Vue.component('icon-rei-cart', {
  template: iconReiCartTmpl,
});

const iconReiChatTmpl = require('../../assets/icons/icon-rei-chat.svg');

const iconReiChat = Vue.component('icon-rei-chat', {
  template: iconReiChatTmpl,
});

const iconReiCheckTmpl = require('../../assets/icons/icon-rei-check.svg');

const iconReiCheck = Vue.component('icon-rei-check', {
  template: iconReiCheckTmpl,
});

const iconReiCloseSmallTmpl = require('../../assets/icons/icon-rei-close-small.svg');

const iconReiCloseSmall = Vue.component('icon-rei-close-small', {
  template: iconReiCloseSmallTmpl,
});

const iconReiCloseTmpl = require('../../assets/icons/icon-rei-close.svg');

const iconReiClose = Vue.component('icon-rei-close', {
  template: iconReiCloseTmpl,
});

const iconReiCollapseTmpl = require('../../assets/icons/icon-rei-collapse.svg');

const iconReiCollapse = Vue.component('icon-rei-collapse', {
  template: iconReiCollapseTmpl,
});

const iconReiDevicesTmpl = require('../../assets/icons/icon-rei-devices.svg');

const iconReiDevices = Vue.component('icon-rei-devices', {
  template: iconReiDevicesTmpl,
});

const iconReiDownArrowTmpl = require('../../assets/icons/icon-rei-down-arrow.svg');

const iconReiDownArrow = Vue.component('icon-rei-down-arrow', {
  template: iconReiDownArrowTmpl,
});

const iconReiEmailTmpl = require('../../assets/icons/icon-rei-email.svg');

const iconReiEmail = Vue.component('icon-rei-email', {
  template: iconReiEmailTmpl,
});

const iconReiErrorTmpl = require('../../assets/icons/icon-rei-error.svg');

const iconReiError = Vue.component('icon-rei-error', {
  template: iconReiErrorTmpl,
});

const iconReiExpandTmpl = require('../../assets/icons/icon-rei-expand.svg');

const iconReiExpand = Vue.component('icon-rei-expand', {
  template: iconReiExpandTmpl,
});

const iconReiExternalLinkTmpl = require('../../assets/icons/icon-rei-external-link.svg');

const iconReiExternalLink = Vue.component('icon-rei-external-link', {
  template: iconReiExternalLinkTmpl,
});

const iconReiHamburgerMenuTmpl = require('../../assets/icons/icon-rei-hamburger-menu.svg');

const iconReiHamburgerMenu = Vue.component('icon-rei-hamburger-menu', {
  template: iconReiHamburgerMenuTmpl,
});

const iconReiHelpTmpl = require('../../assets/icons/icon-rei-help.svg');

const iconReiHelp = Vue.component('icon-rei-help', {
  template: iconReiHelpTmpl,
});

const iconReiInfoTmpl = require('../../assets/icons/icon-rei-info.svg');

const iconReiInfo = Vue.component('icon-rei-info', {
  template: iconReiInfoTmpl,
});

const iconReiInlineSearchTmpl = require('../../assets/icons/icon-rei-inline-search.svg');

const iconReiInlineSearch = Vue.component('icon-rei-inline-search', {
  template: iconReiInlineSearchTmpl,
});

const iconReiLeftArrowTmpl = require('../../assets/icons/icon-rei-left-arrow.svg');

const iconReiLeftArrow = Vue.component('icon-rei-left-arrow', {
  template: iconReiLeftArrowTmpl,
});

const iconReiLocationTmpl = require('../../assets/icons/icon-rei-location.svg');

const iconReiLocation = Vue.component('icon-rei-location', {
  template: iconReiLocationTmpl,
});

const iconReiPlayLargeTmpl = require('../../assets/icons/icon-rei-play-large.svg');

const iconReiPlayLarge = Vue.component('icon-rei-play-large', {
  template: iconReiPlayLargeTmpl,
});

const iconReiPlaySmallTmpl = require('../../assets/icons/icon-rei-play-small.svg');

const iconReiPlaySmall = Vue.component('icon-rei-play-small', {
  template: iconReiPlaySmallTmpl,
});

const iconReiPrintTmpl = require('../../assets/icons/icon-rei-print.svg');

const iconReiPrint = Vue.component('icon-rei-print', {
  template: iconReiPrintTmpl,
});

const iconReiProfileTmpl = require('../../assets/icons/icon-rei-profile.svg');

const iconReiProfile = Vue.component('icon-rei-profile', {
  template: iconReiProfileTmpl,
});

const iconReiRightArrowTmpl = require('../../assets/icons/icon-rei-right-arrow.svg');

const iconReiRightArrow = Vue.component('icon-rei-right-arrow', {
  template: iconReiRightArrowTmpl,
});

const iconReiSearchTmpl = require('../../assets/icons/icon-rei-search.svg');

const iconReiSearch = Vue.component('icon-rei-search', {
  template: iconReiSearchTmpl,
});

const iconReiShareTmpl = require('../../assets/icons/icon-rei-share.svg');

const iconReiShare = Vue.component('icon-rei-share', {
  template: iconReiShareTmpl,
});

const iconReiShippingTmpl = require('../../assets/icons/icon-rei-shipping.svg');

const iconReiShipping = Vue.component('icon-rei-shipping', {
  template: iconReiShippingTmpl,
});

const iconReiSizeChartTmpl = require('../../assets/icons/icon-rei-size-chart.svg');

const iconReiSizeChart = Vue.component('icon-rei-size-chart', {
  template: iconReiSizeChartTmpl,
});

const iconReiSocialFacebookTmpl = require('../../assets/icons/icon-rei-social-facebook.svg');

const iconReiSocialFacebook = Vue.component('icon-rei-social-facebook', {
  template: iconReiSocialFacebookTmpl,
});

const iconReiSocialInstagramTmpl = require('../../assets/icons/icon-rei-social-instagram.svg');

const iconReiSocialInstagram = Vue.component('icon-rei-social-instagram', {
  template: iconReiSocialInstagramTmpl,
});

const iconReiSocialPinterestTmpl = require('../../assets/icons/icon-rei-social-pinterest.svg');

const iconReiSocialPinterest = Vue.component('icon-rei-social-pinterest', {
  template: iconReiSocialPinterestTmpl,
});

const iconReiSocialTwitterTmpl = require('../../assets/icons/icon-rei-social-twitter.svg');

const iconReiSocialTwitter = Vue.component('icon-rei-social-twitter', {
  template: iconReiSocialTwitterTmpl,
});

const iconReiSocialYoutubeTmpl = require('../../assets/icons/icon-rei-social-youtube.svg');

const iconReiSocialYoutube = Vue.component('icon-rei-social-youtube', {
  template: iconReiSocialYoutubeTmpl,
});

const iconReiStar100Tmpl = require('../../assets/icons/icon-rei-star-100.svg');

const iconReiStar100 = Vue.component('icon-rei-star-100', {
  template: iconReiStar100Tmpl,
});

const iconReiStar25Tmpl = require('../../assets/icons/icon-rei-star-25.svg');

const iconReiStar25 = Vue.component('icon-rei-star-25', {
  template: iconReiStar25Tmpl,
});

const iconReiStar50Tmpl = require('../../assets/icons/icon-rei-star-50.svg');

const iconReiStar50 = Vue.component('icon-rei-star-50', {
  template: iconReiStar50Tmpl,
});

const iconReiStar75Tmpl = require('../../assets/icons/icon-rei-star-75.svg');

const iconReiStar75 = Vue.component('icon-rei-star-75', {
  template: iconReiStar75Tmpl,
});

const iconReiSuccessTmpl = require('../../assets/icons/icon-rei-success.svg');

const iconReiSuccess = Vue.component('icon-rei-success', {
  template: iconReiSuccessTmpl,
});

const iconReiTargetTmpl = require('../../assets/icons/icon-rei-target.svg');

const iconReiTarget = Vue.component('icon-rei-target', {
  template: iconReiTargetTmpl,
});

const iconReiTreeArrowTmpl = require('../../assets/icons/icon-rei-tree-arrow.svg');

const iconReiTreeArrow = Vue.component('icon-rei-tree-arrow', {
  template: iconReiTreeArrowTmpl,
});

const iconReiUpArrowTmpl = require('../../assets/icons/icon-rei-up-arrow.svg');

const iconReiUpArrow = Vue.component('icon-rei-up-arrow', {
  template: iconReiUpArrowTmpl,
});

const iconReiVrTmpl = require('../../assets/icons/icon-rei-vr.svg');

const iconReiVr = Vue.component('icon-rei-vr', {
  template: iconReiVrTmpl,
});

const iconReiWarningTmpl = require('../../assets/icons/icon-rei-warning.svg');

const iconReiWarning = Vue.component('icon-rei-warning', {
  template: iconReiWarningTmpl,
});

const iconReiZoomTmpl = require('../../assets/icons/icon-rei-zoom.svg');

const iconReiZoom = Vue.component('icon-rei-zoom', {
  template: iconReiZoomTmpl,
});

export default {
  iconReiAdd,
  iconReiBackorder,
  iconReiCalendar,
  iconReiCall,
  iconReiCartEmpty,
  iconReiCart,
  iconReiChat,
  iconReiCheck,
  iconReiCloseSmall,
  iconReiClose,
  iconReiCollapse,
  iconReiDevices,
  iconReiDownArrow,
  iconReiEmail,
  iconReiError,
  iconReiExpand,
  iconReiExternalLink,
  iconReiHamburgerMenu,
  iconReiHelp,
  iconReiInfo,
  iconReiInlineSearch,
  iconReiLeftArrow,
  iconReiLocation,
  iconReiPlayLarge,
  iconReiPlaySmall,
  iconReiPrint,
  iconReiProfile,
  iconReiRightArrow,
  iconReiSearch,
  iconReiShare,
  iconReiShipping,
  iconReiSizeChart,
  iconReiSocialFacebook,
  iconReiSocialInstagram,
  iconReiSocialPinterest,
  iconReiSocialTwitter,
  iconReiSocialYoutube,
  iconReiStar100,
  iconReiStar25,
  iconReiStar50,
  iconReiStar75,
  iconReiSuccess,
  iconReiTarget,
  iconReiTreeArrow,
  iconReiUpArrow,
  iconReiVr,
  iconReiWarning,
  iconReiZoom,
};
